[project]
name = "lab8"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "altair>=5.4.1",
    "polars>=1.14.0",
    "streamlit>=1.40.1",
]
